WITH checks AS (
    SELECT 'Document count' AS check_name, CAST(6 AS DECIMAL(18,2)) AS expected, CAST((SELECT COUNT_BIG(*) FROM dbo.dim_document) AS DECIMAL(18,2)) AS actual
    UNION ALL SELECT 'Revision count', 8, (SELECT COUNT_BIG(*) FROM dbo.dim_revision)
    UNION ALL SELECT 'Job count', 7, (SELECT COUNT_BIG(*) FROM dbo.fact_job_cost)
    UNION ALL SELECT 'Invoice dispositions', 13, (SELECT COUNT_BIG(*) FROM dbo.invoice_disposition)
    UNION ALL SELECT 'Current publications', 4, (SELECT COUNT_BIG(*) FROM dbo.v_current_catalog)
    UNION ALL SELECT 'Source parseable USD', 11305.00, (SELECT SUM(parsed_amount) FROM dbo.invoice_disposition)
    UNION ALL SELECT 'Matched USD', 8725.00, (SELECT SUM(parsed_amount) FROM dbo.invoice_disposition WHERE disposition = 'Matched')
    UNION ALL SELECT 'Unmatched USD', 480.00, (SELECT SUM(parsed_amount) FROM dbo.invoice_disposition WHERE disposition = 'Unmatched')
    UNION ALL SELECT 'Rejected parseable USD', 2100.00, (SELECT SUM(parsed_amount) FROM dbo.invoice_disposition WHERE disposition = 'Rejected')
    UNION ALL SELECT 'Unparseable rows', 1, (SELECT COUNT_BIG(*) FROM dbo.invoice_disposition WHERE parsed_amount IS NULL)
    UNION ALL SELECT 'Unique job quantity', 10600, (SELECT SUM(quantity) FROM dbo.fact_job_cost)
    UNION ALL SELECT 'Expected cost USD', 8450.00, (SELECT SUM(expected_cost) FROM dbo.fact_job_cost)
    UNION ALL SELECT 'Job actual USD', 8725.00, (SELECT SUM(actual_cost) FROM dbo.fact_job_cost)
    UNION ALL SELECT 'Variance USD', 275.00, (SELECT SUM(variance) FROM dbo.fact_job_cost)
    UNION ALL SELECT 'Credit preserved', -100.00, (SELECT parsed_amount FROM dbo.invoice_disposition WHERE source_line_id = 'L007')
    UNION ALL SELECT 'Job J001 net cost', 2000.00, (SELECT actual_cost FROM dbo.fact_job_cost WHERE job_id = 'J001')
    UNION ALL SELECT 'Job J003 additional line', 3250.00, (SELECT actual_cost FROM dbo.fact_job_cost WHERE job_id = 'J003')
    UNION ALL SELECT 'Duplicate reason', 1, (SELECT COUNT_BIG(*) FROM dbo.invoice_disposition WHERE source_line_id = 'L009' AND reason = 'DUPLICATE_LINE')
    UNION ALL SELECT 'Vendor mismatch reason', 1, (SELECT COUNT_BIG(*) FROM dbo.invoice_disposition WHERE source_line_id = 'L013' AND reason = 'VENDOR_MISMATCH')
    UNION ALL SELECT 'Missing owner', 1, (SELECT SUM(missing_owner) FROM dbo.report_catalog)
    UNION ALL SELECT 'D001 current revision', 1, (SELECT COUNT_BIG(*) FROM dbo.v_current_catalog WHERE document_id = 'D001' AND current_revision_id = 'R002')
    UNION ALL SELECT 'D003 future draft excluded', 1, (SELECT COUNT_BIG(*) FROM dbo.v_current_catalog WHERE document_id = 'D003' AND current_revision_id = 'R004')
)
SELECT check_name, expected, actual FROM checks WHERE actual IS NULL OR actual <> expected;